### ISSUE TITLE
Korekuta is failing to include csv files in payloads

### ISSUE THREAD

**Issue by dccurtis** [project-koku/korekuta#75]
Investigate (and fix) whether or not it's possible for korekuta to send a payload with missing csv files.

See Also: https://github.com/project-koku/masu/issues/464 and PR to address it on the listener side https://github.com/project-koku/masu/pull/467

This issue was seen in production recently I was able to access the temporary extraction directory to see the contents of the payload.

The csv files appear to be missing from the payload despite their file names being in the manifest.
```
Task exception was never retrieved
--
  | future: <Task finished coro=<process_messages() done, defined at /opt/app-root/src/masu/external/kafka_msg_handler.py:290> exception=FileNotFoundError(2, 'No such file or directory')>
  | Traceback (most recent call last):
  | File "/opt/app-root/src/masu/external/kafka_msg_handler.py", line 303, in process_messages
  | status, report_meta = handle_message(msg)
  | File "/opt/app-root/src/masu/external/kafka_msg_handler.py", line 224, in handle_message
  | report_meta = extract_payload(value['url'])
  | File "/opt/app-root/src/masu/external/kafka_msg_handler.py", line 140, in extract_payload
  | shutil.copy(payload_source_path, payload_destination_path)
  | File "/opt/app-root/lib64/python3.6/shutil.py", line 241, in copy
  | copyfile(src, dst, follow_symlinks=follow_symlinks)
  | File "/opt/app-root/lib64/python3.6/shutil.py", line 120, in copyfile
  | with open(src, 'rb') as fsrc:
  | FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpex3ikj56/2f72a597-e458-5f4e-9103-b7b7af35b993/bbe37a8c-f1fa-5f6e-9a70-ce1d9216129a_openshift_usage_report.0.csv'


(app-root) sh-4.2$ ls /tmp/tmpex3ikj56/2f72a597-e458-5f4e-9103-b7b7af35b993
manifest.json
(app-root) sh-4.2$ ls /tmp/tmpex3ikj56/2f72a597-e458-5f4e-9103-b7b7af35b993
manifest.json
(app-root) sh-4.2$

(app-root) sh-4.2$ cat /tmp/tmpex3ikj56/2f72a597-e458-5f4e-9103-b7b7af35b993/manifest.json
{
    "files": ["bbe37a8c-f1fa-5f6e-9a70-ce1d9216129a_openshift_usage_report.0.csv", "bbe37a8c-f1fa-5f6e-9a70-ce1d9216129a_openshift_usage_report.1.csv"],
    "date": "2019-06-14T16:57:56Z",
    "uuid": "bbe37a8c-f1fa-5f6e-9a70-ce1d9216129a",
    "cluster_id": "2f72a597-e458-5f4e-9103-b7b7af35b993"
}
(app-root) sh-4.2$
```

**Comment by adberglund** [comment]
I think we need a check in the collect role after downloading reports from operator metering to actually make sure there are files created. If there are no files we should skip sending the payload through the Insights Client.
